server:
  port: 8761
eureka:
  client:
    # 是否将自己注册到Eureka Server，默认为true
    register-with-eureka: false
    # 是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
    serverUrl:
      # 设置与Eureka交互的地址，查询服务和注册服务都依赖这个地址
      defaultZone: http://localhost:8761/eureka/